# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0004_termsandconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingaddon',
            name='add_on',
        ),
        migrations.RemoveField(
            model_name='bookingaddon',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='BookingAddOn',
        ),
    ]
