# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0005_auto_20170423_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(choices=[('5', 'Saturday'), ('6', 'Sunday')]),
        ),
    ]
