# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0006_auto_20170423_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='puddlesbooking.Venue'),
        ),
        migrations.AddField(
            model_name='disableddates',
            name='timeslots',
            field=models.ManyToManyField(to='puddlesbooking.Timeslot'),
        ),
    ]
