# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0009_auto_20170501_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addons',
            field=models.ManyToManyField(to='puddlesbooking.AddOn'),
        ),
    ]
