# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0010_booking_addons'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='venue',
            name='catering',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='own_food',
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='parking',
            field=models.CharField(default='ddd', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='price_plans',
            field=models.ManyToManyField(to='puddlesbooking.PricePlan'),
        ),
    ]
