# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0011_auto_20170501_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
