# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0012_timeslot_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
