# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0013_venue_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='puddlesbooking.Theme'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='puddlesbooking.Timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue', to='puddlesbooking.Venue'),
        ),
    ]
