# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0014_auto_20170502_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
