# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0017_addon_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='booking',
            name='price_plan',
            field=models.CharField(default='BYO Food', max_length=20),
            preserve_default=False,
        ),
    ]
