# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlesbooking', '0018_auto_20170505_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_babies',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
